db.url=jdbc:mysql://localhost:3306/expense_db?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
db.username=root
db.password=Ledung/02

db.pool.maximumPoolSize=10
db.pool.minimumIdle=2
db.pool.connectionTimeout=30000

app.name=Expense Manager

logging.level.org.springframework.security=DEBUG